name: Debugger Action

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions: false | tmate | ngrok'
        required: false
        default: 'false'
        
evn:
  INIT_RUN: false
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  
jobs:
  prod-check:
    if: ${{ evn.INIT_RUN == false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
