name: Debugger Action

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions: false | tmate | ngrok'
        required: false
        default: 'false'

env:
  INIT_RUN: false
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: if [ -f /init_marked ]; then env.INIT_RUN=true; fi

  job2:
    needs: job1
    if: ${{ env.INIT_RUN == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Disk Info
        run: |
          df -hT
      - name: Done
        run: echo "Done"
