name: Debugger Action

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions: false | tmate | ngrok'
        required: false
        default: 'false'

env:
  INIT_RUN: false
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: if [ -f /init_marked ]; then env.INIT_RUN=true; fi


  job2:
    needs: job1
    if: ${{ env.INIT_RUN == false }}
    runs-on: ubuntu-latest
    setps:
      - name: Marked Info
        run: |
          echo init > /init_marked
          cat /init_marked

  job3:
    needs: [job1, job2]
    if: ${{ env.INIT_RUN == true }}
    runs-on: ubuntu-latest
    setps:
      - name: Marked Info
        run: |
          cat /init_marked  | wc -l >> /init_marked
          cat /init_marked
