name: civen-test
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
     - uses: actions/checkout@main

     - name: Disk Info
       run: |
         df -hT
         fdisk -l
