name: Debugger Action

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions: false | tmate | ngrok'
        required: false
        default: 'false'

evn:
  INIT_RUN: false
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git

jobs:
  job1:
  runs-on: ubuntu-latest
  setps:
    run: if [ -f /init_marked ]; then evn.INIT_RUN=true; fi
