name: Debugger Action

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Disk Info
       run: |
         df -hT
    
     - name: Done
       run: echo "Done"
