name: Debugger Action

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions: false | tmate | ngrok'
        required: false
        default: 'false'

env:
  INIT_RUN: 'false'
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: if [ -f /init_marked ]; then env.INIT_RUN=true; fi

  job2:
    if: always()
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: |
          echo init > ./init_marked
          cat ./init_marked

  job3:
    if: always()
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Marked Info
        run: |
          cat ./init_marked  | wc -l >> ./init_marked
          cat ./init_marked
          echo $INIT_RUN
