name: Debugger Action

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions: false | tmate | ngrok'
        required: true
        default: 'false'

permissions: write-all

env:
  INIT_RUN: false
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  GITHUB_TOKEN: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: if [ -f init_marked.txt ]; then echo $PATH; fi

  job2:
    if: always()
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Marked Info
        run: |
          echo init > init_marked.txt
          cat init_marked.txt

  job3:
    if: always()
    needs: [job1, job2]
    runs-on: ubuntu-latest

    steps:
      - name: Marked Info
        run: |
          cat init_marked.txt  | wc -l >> init_marked.txt
          cat init_marked.txt
          tar -cvf my_files.tar init_marked.txt
          echo $INIT_RUN

      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: my_files
          path: my_files.tar.gz

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test_v1
          body_path: init_marked.txt
          files: my_files.tar.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
