name: Sshd

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions: false | tmate | ngrok'
        required: true
        default: 'false'

permissions: write-all

env:
  INIT_RUN: false
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  GITHUB_TOKEN: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: tmate1 - sshd
        if: (github.event.inputs.ssh == 'tmate1')
        run: touch /tmp/keepalive
        uses: csexton/debugger-action@master
