name: Debugger Action2

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions: tmate1 | tmate2 | ngrok'
        required: true
        default: 'false'

permissions: write-all

env:
  INIT_RUN: false
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  NGROK_SH: github-actions-ngrok.sh


jobs:
  tmate:
    runs-on: ubuntu-latest

    steps:
      - name: tmate1 - sshd
        if: (github.event.inputs.ssh == 'tmate1')
        run: touch /tmp/keepalive
        uses: csexton/debugger-action@master

      - name: tmate2 - sshd
        if: (github.event.inputs.ssh == 'tmate2')
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 14400
