name: SSHD

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions: tmate1 | tmate2 | ngrok | shell'
        required: true
        default: 'tmate1'

permissions: write-all

env:
  INIT_RUN: false
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  NGROK_SH: github-actions-ngrok.sh
  RUN_SH: run.sh


jobs:
  tmate:
    runs-on: ubuntu-latest

    steps:
      - name: INIT
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo $GITHUB_WORKSPACE
          
      - name: Working Dir
        working-directory: /workdir
          
      - name: Run Shell
        if: (github.event.inputs.ssh == 'shell')
        run: |
          echo "hello shell!"
          echo $PWD
          sh $GITHUB_WORKSPACE/$RUN_SH
          echo $GITHUB_WORKSPACE

      - name: tmate1 - sshd
        if: (github.event.inputs.ssh == 'tmate1')
        uses: csexton/debugger-action@master

      - name: tmate2 - sshd
        if: (github.event.inputs.ssh == 'tmate2')
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 14400

      - name: ngrok - sshd
        if: (github.event.inputs.ssh == 'ngrok')
        
        env:
          ### https://dashboard.ngrok.com/get-started/your-authtoken # GET NGROK TOKEN
          NGROK_TOKEN: 1vK9OpmKzlSYS0T4y8Lp7wkRJZz_73YoJoXvH4RoEiUq9ji3P

          ### https://ngrok.com/docs#global-locations # NGROK SERVER REGION [us, eu, au, ap, sa, jp, in]
          NGROK_REGION: ap

          ### SSH 登录密码
          SSH_PASSWORD: test-password
          
        run: |
          curl -fsSL https://raw.githubusercontent.com/civenz/actions-openwrt/main/github-actions-ngrok.sh -o ngrok.sh
          chmod +x ngrok.sh
          ./ngrok.sh
        shell: bash
        
      - name: ngrok - sleep
        if: (github.event.inputs.ssh == 'ngrok')
        run: |
          sleep 1200
          cp /home/runner/openwrt-sdk/bin/packages/x86_64/base/luci-app-xray_1.0.10-1_x86_64.ipk luci-app-xray_1.0.10-1_x86_64.ipk
          tar -czvf my_files.tar.gz luci-app-xray_1.0.10-1_x86_64.ipk
        
      - name: Upload File
        if: (github.event.inputs.ssh == 'ngrok')
        uses: actions/upload-artifact@v2
        with:
          name: my_files
          path: my_files.tar.gz
          
